import{a as p,S as m}from"./assets/vendor-DdMkFUeo.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const h="49484019-11a5d61f6cd196bafa2004bf7",g="https://pixabay.com/api/",b=15;async function y(o,t=1){const n={key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:b,page:t};try{return(await p.get(g,{params:n})).data}catch(s){return console.error("❌ Fetch error:",s),{hits:[],totalHits:0}}}let L=new m(".gallery a");function f(o,t=!1){const n=document.querySelector(".gallery"),s=o.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}">
                <div class="info">
                    <p>❤️ ${e.likes}  👁️ ${e.views}  💬 ${e.comments}  ⬇️ ${e.downloads}</p>
                </div>
            </a>
        </li>
    `).join("");t?n.insertAdjacentHTML("beforeend",s):n.innerHTML=s,L.refresh()}const S=document.querySelector(".form"),v=document.querySelector("#search"),q=document.querySelector(".gallery"),i=document.querySelector(".load-more"),c=document.querySelector(".loader");let l="",a=1,u=0;S.addEventListener("submit",async o=>{if(o.preventDefault(),l=v.value.trim(),!l)return;a=1,q.innerHTML="",i.style.display="none",c.style.display="block";const t=await y(l,a);if(c.style.display="none",t.hits.length===0){alert("No images found. Try another search.");return}u=t.totalHits,f(t.hits),a*15<u&&(i.style.display="block")});i.addEventListener("click",async()=>{a++,c.style.display="block";const o=await y(l,a);c.style.display="none",f(o.hits,!0),a*15>=u&&(i.style.display="none",alert("We're sorry, but you've reached the end of search results.")),w()});function w(){var t;const o=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||200;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
